name: debug_build
on:
  workflow_run:
    workflows: ["Test Workflow"]
    types:
      - completed
jobs:
  debug_build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Setup a local virtual environment (if no poetry.toml file)
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install the project dependencies
        run: poetry install --all-extras
      - name: build app
        run: poetry build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fastanime_debug_build
          path: |
            dist
            !dist/*.whl
      # - name: Run the automated tests (for example)
      # run: poetry run pytest -v
